name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --console --name="ExpiryCalculator" --clean main.py
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: expiry-calculator-windows
        path: dist/ExpiryCalculator.exe
        
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: build-windows
    
    steps:
    - name: Download Windows executable
      uses: actions/download-artifact@v4
      with:
        name: expiry-calculator-windows
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ExpiryCalculator.exe
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        body: |
          Expiry Date Calculator
          
          Features:
          - Input current date and shelf life
          - Calculate expiry date
          - Show remaining days
          - Expiry reminders
          
          Build: ${{ github.run_number }}
          Date: ${{ github.event.head_commit.timestamp }}